name: Secrets and Variables

on:
    workflow_dispatch


jobs:
    top-secret:
        runs-on: ubuntu-latest
        env:
            MY_APP_ID: ${{ vars.APP_ID }}

        steps:
            - name: Read my variable
              run: echo "My APP_ID value is ${{ vars.APP_ID}}"

            - name: Tell me a secret!CLose hio 
              run: echo "My existsing secret is ${{secrets.API_KEY}}"
            - name: Unset secret
              run: echo "My unknown secret is ${{ secrets.DOES_NOT_EXIST }}"
            - name: Read an env variable
              run: echo "My APP_ID value is ${{ env.APP_ID }} (also accessible as $MY_APP_ID)"
      

    
    top-secret-production:
        runs-on: ubuntu-latest
        environment: staging
        env:
        APP_ID: ${{ vars.APP_ID }}